name: Deploy to Azure Container Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-azurewebapp
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: AzureWebApp-RG
  ACR_NAME: azurewebappregistry
  CONTAINER_APP_NAME: azurewebapp
  CONTAINER_APP_ENV: AzureWebApp-CAE
  LOCATION: northeurope
  IMAGE_NAME: azurewebapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Azure login via OIDC ---
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # --- Diagnostics (optional but useful) ---
      - name: Who am I in Azure?
        run: |
          echo "== Account =="
          az account show --output table
          echo "== Raw principal =="
          az account show --query user -o json

      - name: Check access to resources
        run: |
          echo "== Resource Group =="
          az group show -n $AZURE_RESOURCE_GROUP --out table
          echo "== ACR =="
          az acr show -n $ACR_NAME -g $AZURE_RESOURCE_GROUP --out table
          echo "== Container App (may not exist yet) =="
          az containerapp show -n $CONTAINER_APP_NAME -g $AZURE_RESOURCE_GROUP --out table || true

      # --- Build & push to ACR using OIDC (no registry passwords) ---
      - name: ACR login (token via az)
        run: az acr login --name $ACR_NAME

      - name: Build image
        run: |
          IMAGE="$ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .

      - name: Push image
        run: |
          IMAGE="$ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "Pushing $IMAGE"
          docker push "$IMAGE"

      # --- Update Container App to use the new image ---
      # Requires the app to already be configured to pull via its managed identity:
      #   az containerapp identity assign -g RG -n APP --system-assigned
      #   az role assignment create --assignee <APP_PRINCIPAL_ID> --role AcrPull --scope <ACR_ID>
      #   az containerapp registry set -g RG -n APP --server <ACR_LOGIN_SERVER> --identity system
      - name: Update Container App
        run: |
          IMAGE="$ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          az containerapp update \
            -g $AZURE_RESOURCE_GROUP \
            -n $CONTAINER_APP_NAME \
            --image "$IMAGE" \
            --output table

      # --- Show the public URL ---
      - name: Show app URL
        if: always()
        run: |
          FQDN=$(az containerapp show -g $AZURE_RESOURCE_GROUP -n $CONTAINER_APP_NAME --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || true)
          if [ -n "$FQDN" ]; then
            echo "✅ Deployed: https://$FQDN"
          else
            echo "Deployment finished. If this is the first create, the FQDN may appear shortly."
          fi
